apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: qlgjv6aiz-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:e0f09eedde55d7af83dce447c3c4f1a0d48e5a99@sha256:aa1e65f1316de9be8f4fb8d520696f2fd758ee901c900f09baab720211a52ebc
          name: container-image
